name:  complete cicd job
on: push

jobs:
  Testing:
    runs-on: myrunner
    steps:
      - name: Code checkout
        uses: actions/checkout@v4
      - name: install mvn
        run : sudo apt install maven -y
      
      - name: testbuild
        run : mvn clean install
      - name: test
        run: mvn test
  Build:
     runs-on: myrunner
     needs: Testing
     steps:
      - name: Code checkout
        uses: actions/checkout@v4
      - name: install docker
        run : |
         # Add Docker's official GPG key:
         sudo apt-get update
         sudo apt-get install ca-certificates curl
         sudo install -m 0755 -d /etc/apt/keyrings
         sudo curl -fsSL https://download.docker.com/linux/ubuntu/gpg -o /etc/apt/keyrings/docker.asc
         sudo chmod a+r /etc/apt/keyrings/docker.asc
         sudo apt-get install docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
         

         # Add the repository to Apt sources:
         echo \
         "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu \
         $(. /etc/os-release && echo "${UBUNTU_CODENAME:-$VERSION_CODENAME}") stable" | \
         sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
         sudo apt-get update
         sudo usermod -aG docker ubuntu
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERUSERNAME }}
          password: ${{ secrets.DOCKERPASSWD }}
      -  name: Build and push
         uses: docker/build-push-action@v6
         with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ vars.DOCKERUSERNAME }}/cicd:${{ github.sha }}
  Deploy:
      runs-on: myrunner
      needs: Build
      steps:
      - name: Code checkout
        uses: actions/checkout@v4       
      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
      - name: setup kubeconfig
        uses: azure/k8s-set-context@v3
        with:
         method: kubeconfig
         kubeconfig: ${{ secrets.KUBECONFIG }}
         
      - name: Deploy to Kubernetes
        run: |
        
          kubectl get nodes
          
      