name: deploy to lambda

on:
  push:
    branches: [ master ]   # auto deploy to dev on push
  workflow_dispatch:        # manual trigger for prod deploy
    inputs:
      environment:
        description: "Select environment to deploy"
        required: true
        default: "eu"
        type: choice
        options:
          - us
          - eu

jobs:
  build:
    name: Build and Package
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22.x

      - name: Install dependencies and build
        run: npm ci

      - name: Create zip bundle
        uses: montudor/action-zip@v0.1.0
        with:
          args: zip -qq -r ./bundle.zip ./

      - name: Upload bundle as artifact
        uses: actions/upload-artifact@v3
        with:
          name: bundle
          path: bundle.zip

  deploy-dev:
    name: Deploy to Dev
    needs: build
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: bundle

      - name: Deploy Lambda (Dev)
        uses: appleboy/lambda-action@master
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: us-east-1
          function_name: cryptlexReleaseHandlerDev
          zip_file: bundle.zip

  deploy-prod-us:
    name: Deploy to Prod (US)
    needs: build
    if: github.event_name == 'workflow_dispatch' && github.event.inputs.environment == 'us'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: bundle

      - name: Deploy Lambda (Prod US)
        uses: appleboy/lambda-action@master
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: us-east-1
          function_name: CryptlexReleaseHandler
          zip_file: bundle.zip

  deploy-prod-eu:
    name: Deploy to Prod (EU)
    needs: build
    if: github.event_name == 'workflow_dispatch' && github.event.inputs.environment == 'eu'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: bundle

      - name: Deploy Lambda (Prod EU)
        uses: appleboy/lambda-action@master
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: eu-west-1
          function_name: cryptlexReleaseHandlerEU
          zip_file: bundle.zip
