name: deploy to lambda

on:
  push:
    tags:
      - '1.*'
    branches:
      - master
  workflow_dispatch:   # 👈 allows manual trigger from GitHub UI

jobs:
  deploy-lambda:
    name: build and deploy lambda
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22.x

      - name: npm install and build
        run: npm ci

      - name: zip
        uses: montudor/action-zip@v0.1.0
        with:
          args: zip -qq -r ./bundle.zip ./

      # ✅ Dev deploy (only on master branch)
      - name: deploy to dev
        if: github.ref == 'refs/heads/master'
        uses: appleboy/lambda-action@master
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: us-east-1
          function_name: cryptlexReleaseHandlerDev
          zip_file: bundle.zip

      # ✅ Prod deploy (only when pushing tag "1.*")
      - name: deploy to prod
        if: startsWith(github.ref, 'refs/tags/1.')
        uses: appleboy/lambda-action@master
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: us-east-1
          function_name: CryptlexReleaseHandler
          zip_file: bundle.zip

      # ✅ Prod EU deploy (only when pushing tag "1.*")
      - name: deploy to prod EU
        if: startsWith(github.ref, 'refs/tags/1.')
        uses: appleboy/lambda-action@master
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: eu-central-1   # 👈 assuming EU deployment should be in Frankfurt
          function_name: cryptlexReleaseHandlerEU
          zip_file: bundle.zip
