name:  complete cicd job
on: push

jobs:
  Testing:
    runs-on: ubuntu-latest
    steps:
      - name: Code checkout
        uses: actions/checkout@v4
      
      
      - name: testbuild
        run : mvn clean install
      - name: test
        run: mvn test
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERUSERNAME }}
          password: ${{ secrets.DOCKERPASSWD }}
      -  name: Build and push
         uses: docker/build-push-action@v6
         with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ vars.DOCKERUSERNAME }}/cicd:${{ github.sha }}
      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
      - uses: azure/k8s-set-context@v4
        with:
         method: kubeconfig
         kubeconfig: ${{ secrets.KUBECONFIG }}
         #decode-kubeconfig: true
      - name: Deploy to Kubernetes
        run: |
        
          kubectl apply -f kubernetes/app.yml
          
      