name:  complete cicd job
on: push

jobs:
  Testing:
    runs-on: ubuntu-latest
    steps:
      - name: Code checkout
        uses: actions/checkout@v4
      
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: testbuild
        run : mvn clean install
      - name: test
        run: mvn test
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERUSERNAME }}
          password: ${{ secrets.DOCKERPASSWD }}
      -  name: Build and push
         uses: docker/build-push-action@v6
         with:
          #context: ./cicd-deploy-kube
          file: ./cicd-deploy-kube/Dockerfile
          push: true
          tags: ${{ vars.DOCKERUSERNAME }}/cicd:${{ github.sha }}
      