name: deploy to lambda

on:
  push:
    branches: [ master ]
  workflow_dispatch:  
    inputs:
      environment:
        description: "Select environment to deploy"
        required: true
        default: "EU"
        type: choice
        options:
          - EU
          - US

jobs:
  deploy-lambda:
    name: build and deploy lambda
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22.x

      - name: npm install and build
        run: npm ci

      - name: zip
        uses: montudor/action-zip@v0.1.0
        with:
          args: zip -qq -r ./bundle.zip ./

      # ✅ Deploy dev only on push
      - name: deploy to dev
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        uses: appleboy/lambda-action@master
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: us-east-1
          function_name: cryptlexReleaseHandlerDev
          zip_file: bundle.zip

      # ✅ Deploy prod only when triggered manually with US selected
      - name: deploy to prod
        if: github.event_name == 'workflow_dispatch' && inputs.environment == 'US'
        uses: appleboy/lambda-action@master
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: us-east-1
          function_name: CryptlexReleaseHandler
          zip_file: bundle.zip

      # ✅ Deploy prod EU only when triggered manually with EU selected
      - name: deploy to prod EU
        if: github.event_name == 'workflow_dispatch' && inputs.environment == 'EU'
        uses: appleboy/lambda-action@master
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: eu-central-1
          function_name: cryptlexReleaseHandlerEU
          zip_file: bundle.zip
