name: deploy to lambda

on:
  push:
    branches: [ master ]   # auto deploy Dev
  workflow_dispatch:        # manual deploy Prod
    inputs:
      environment:
        description: "Select environment to deploy"
        required: true
        default: "EU"
        type: choice
        options:
          - EU
          - US

jobs:
  deploy-lambda:
    name: Build and Deploy Lambda
    runs-on: ubuntu-latest
    steps:
      # Checkout code
      - uses: actions/checkout@v3

      # Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22.x

      # Install dependencies
      - name: Install dependencies and build
        run: npm install   # use npm ci if you commit package-lock.json

      # Create bundle.zip
      - name: Zip source
        run: zip -qq -r ./bundle.zip ./

      # Unzip bundle into dist/
      - name: Unzip bundle
        run: |
          mkdir -p dist
          unzip bundle.zip -d dist

      # ======================
      # Deploy to Dev (on push)
      # ======================
      - name: Configure AWS credentials (Dev)
        if: github.ref == 'refs/heads/master'
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Deploy Lambda (Dev)
        if: github.ref == 'refs/heads/master'
        uses: aws-actions/aws-lambda-deploy@v1
        with:
          function-name: cryptlexReleaseHandlerDev
          code-artifacts-dir: dist
          runtime: nodejs22.x
          handler: index.handler

      # ======================
      # Deploy to Prod (manual)
      # ======================
      - name: Configure AWS credentials (Prod)
        if: github.event_name == 'workflow_dispatch'
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_LAMBDA_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_LAMBDA_SECRET_ACCESS_KEY }}
          aws-region: ${{ github.event.inputs.environment == 'EU' && 'eu-west-1' || 'us-east-1' }}

      - name: Deploy Lambda (Prod)
        if: github.event_name == 'workflow_dispatch'
        uses: aws-actions/aws-lambda-deploy@v1
        with:
          function-name: ${{ github.event.inputs.environment == 'EU' && 'cryptlexReleaseHandlerEU' || 'CryptlexReleaseHandler' }}
          code-artifacts-dir: dist
          runtime: nodejs22.x
          handler: index.handler
