name: deploy to lambda

on:
  push:
    branches: [ master ]
  workflow_dispatch:  
    inputs:
      environment:
        description: "Select environment to deploy"
        required: true
        default: "EU"
        type: choice
        options:
          - EU
          - US

jobs:
  deploy-lambda:
    name: build and deploy lambda
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22.x

      - name: npm install and build
        run: npm ci

      - name: zip
        uses: montudor/action-zip@v0.1.0
        with:
          args: zip -qq -r ./bundle.zip ./
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
        
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws-region: us-east-1


 
      - name: Deploy to dev
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        uses: aws-actions/aws-lambda-deploy@v1
        with:
          function-name: cryptlexReleaseHandlerDev
          code-artifacts-dir: ./dist

     
      - name: Deploy to prod US
        if: github.event_name == 'workflow_dispatch' && inputs.environment == 'US'
        uses: aws-actions/aws-lambda-deploy@v1
        with:
          function-name: CryptlexReleaseHandler
          code-artifacts-dir: ./dist

     
      - name: Deploy to prod EU
        if: github.event_name == 'workflow_dispatch' && inputs.environment == 'EU'
        uses: aws-actions/aws-lambda-deploy@v1
        with:
          function-name: cryptlexReleaseHandlerEU
          code-artifacts-dir: ./dist


