name: deploy to lambda

on:
  push:
    branches: [ master ]   # auto deploy to dev
  workflow_dispatch:        # manual deploy for prod
    inputs:
      environment:
        description: "Select environment to deploy"
        required: true
        default: "EU"
        type: choice
        options:
          - EU
          - US

jobs:
  deploy-lambda:
    name: Build and Deploy Lambda
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22.x

      - name: Install dependencies and build
        run: npm install   # use npm ci if package-lock.json exists

      - name: Prepare dist folder
        run: |
          mkdir -p dist
          cp -r . dist/

      # Deploy Dev automatically on master branch
      - name: Configure AWS credentials (Dev)
        if: github.ref == 'refs/heads/master'
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Deploy Lambda (Dev)
        if: github.ref == 'refs/heads/master'
        uses: aws-actions/aws-lambda-deploy@v1
        with:
          function-name: cryptlexReleaseHandlerDev
          code-artifacts-dir: dist
          runtime: nodejs22.x
          handler: index.handler

      # Deploy Prod manually via workflow_dispatch
      - name: Configure AWS credentials (Prod)
        if: github.event_name == 'workflow_dispatch'
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_LAMBDA_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_LAMBDA_SECRET_ACCESS_KEY }}
          aws-region: ${{ github.event.inputs.environment == 'EU' && 'eu-west-1' || 'us-east-1' }}

      - name: Deploy Lambda (Prod)
        if: github.event_name == 'workflow_dispatch'
        uses: aws-actions/aws-lambda-deploy@v1
        with:
          function-name: ${{ github.event.inputs.environment == 'EU' && 'cryptlexReleaseHandlerEU' || 'CryptlexReleaseHandler' }}
          code-artifacts-dir: dist
          runtime: nodejs22.x
          handler: index.handler
