name: deploy to lambda

on:
  push:
    branches: [ master ]   # auto deploy to dev on push
  workflow_dispatch:        # manual trigger for prod deploy
    inputs:
      environment:
        description: "Select environment to deploy"
        required: true
        default: "eu"
        type: choice
        options:
          - us
          - eu

jobs:
  build:
    name: Build and Package
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22.x

      - name: Install dependencies and build
        run: npm ci

      - name: Create zip bundle
        run: |
          zip -qq -r ./bundle.zip ./

      - name: Upload bundle as artifact
        uses: actions/upload-artifact@v4   # ✅ updated
        with:
          name: bundle
          path: bundle.zip

  deploy-dev:
    name: Deploy to Dev
    needs: build
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4   # ✅ updated
        with:
          name: bundle

      - name: Configure AWS credentials (Dev)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Deploy Lambda (Dev)
        uses: aws-actions/aws-lambda-deploy@v1   # ✅ replaced
        with:
          function-name: cryptlexReleaseHandlerDev
          code: bundle.zip
          runtime: nodejs22.x
          handler: index.handler

  deploy-prod-us:
    name: Deploy to Prod (US)
    needs: build
    if: github.event_name == 'workflow_dispatch' && github.event.inputs.environment == 'us'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4   # ✅ updated
        with:
          name: bundle

      - name: Configure AWS credentials (Prod US)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Deploy Lambda (Prod US)
        uses: aws-actions/aws-lambda-deploy@v1   # ✅ replaced
        with:
          function-name: CryptlexReleaseHandler
          code: bundle.zip
          runtime: nodejs22.x
          handler: index.handler

  deploy-prod-eu:
    name: Deploy to Prod (EU)
    needs: build
    if: github.event_name == 'workflow_dispatch' && github.event.inputs.environment == 'eu'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4   # ✅ updated
        with:
          name: bundle

      - name: Configure AWS credentials (Prod EU)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-1

      - name: Deploy Lambda (Prod EU)
        uses: aws-actions/aws-lambda-deploy@v1   # ✅ replaced
        with:
          function-name: cryptlexReleaseHandlerEU
          code: bundle.zip
          runtime: nodejs22.x
          handler: index.handler
